"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { LevelBadge, StatusBadge } from "@/components/Badges";
import { caseStatuses, judgmentLevels, KnowledgeCase, managementCategories } from "@/lib/types";
import { loadCases } from "@/lib/storage";

export default function CasesPage() {
  const [cases, setCases] = useState<KnowledgeCase[]>([]); const [keyword, setKeyword] = useState(""); const [category, setCategory] = useState(""); const [level, setLevel] = useState(""); const [status, setStatus] = useState(""); const [order, setOrder] = useState("new");
  useEffect(() => setCases(loadCases()), []);
  const filtered = useMemo(() => cases.filter((item) => { const text = `${item.title} ${item.projectName} ${item.managementCategory} ${item.workCategory} ${item.tags.join(" ")}`.toLowerCase(); return (!keyword || text.includes(keyword.toLowerCase())) && (!category || item.managementCategory === category) && (!level || item.judgmentLevel === level) && (!status || item.status === status); }).sort((a, b) => order === "new" ? b.recordedAt.localeCompare(a.recordedAt) : a.recordedAt.localeCompare(b.recordedAt)), [cases, keyword, category, level, status, order]);
  return <AppShell><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-[#163047] sm:text-3xl">事例一覧</h1><p className="mt-2 text-sm text-slate-600">記録された現場判断を検索・確認できます。</p></div><Link href="/cases/new" className="inline-flex min-h-11 items-center justify-center rounded-lg bg-[#176b87] px-4 font-bold text-white hover:bg-[#11566d]">＋ 新規登録</Link></div>
  <section className="mb-6 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><input aria-label="キーワード検索" value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="キーワード検索" /><Filter value={category} change={setCategory} label="管理分類" values={managementCategories} /><Filter value={level} change={setLevel} label="判断レベル" values={judgmentLevels} /><Filter value={status} change={setStatus} label="ステータス" values={caseStatuses} /><select aria-label="並び替え" value={order} onChange={(e) => setOrder(e.target.value)}><option value="new">新しい順</option><option value="old">古い順</option></select></div></section>
  <p className="mb-3 text-sm text-slate-600">{filtered.length}件の事例</p><div className="grid gap-4 md:grid-cols-2">{filtered.map((item) => <CaseCard key={item.id} item={item} />)}</div>{filtered.length === 0 && <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">条件に一致する事例はありません。</div>}</AppShell>;
}
function Filter({ value, change, label, values }: { value: string; change: (v: string) => void; label: string; values: readonly string[] }) { return <select aria-label={label} value={value} onChange={(e) => change(e.target.value)}><option value="">{label}：すべて</option>{values.map((v) => <option key={v}>{v}</option>)}</select>; }
function CaseCard({ item }: { item: KnowledgeCase }) { return <Link href={`/cases/detail/?id=${item.id}`} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-[#176b87] hover:shadow"><div className="flex flex-wrap gap-2"><LevelBadge level={item.judgmentLevel} /><StatusBadge status={item.status} /></div><h2 className="mt-3 text-lg font-bold text-slate-800">{item.title}</h2><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-2 text-sm"><div><dt className="text-slate-500">現場名</dt><dd className="mt-0.5 text-slate-700">{item.projectName || "—"}</dd></div><div><dt className="text-slate-500">管理分類・工種</dt><dd className="mt-0.5 text-slate-700">{item.managementCategory} {item.workCategory && `／${item.workCategory}`}</dd></div><div><dt className="text-slate-500">登録日</dt><dd className="mt-0.5 text-slate-700">{item.recordedAt}</dd></div></dl>{item.tags.length > 0 && <div className="mt-4 flex flex-wrap gap-1.5">{item.tags.map((tag) => <span key={tag} className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">#{tag}</span>)}</div>}</Link>; }
